### ISSUE TITLE
can't compile vue-component-creator-plugin

### ISSUE THREAD

**Issue by masteor** [faebeee/vue-component-creator-plugin#10]
Hello, Fabian

my name is Andrey, I am a beginner Javascript developer, I liked your vue-component-creator plugin, but I wanted to change it a little for my project.

I downloaded your repository: https://github.com/faebeee/vue-component-creator-plugin.git, installed InteliJ Idea, opened your project, tried to compile, but failed

I fixed the imports, for this I downloaded the following libraries:
 
editor-ui-api-142.1
jdom-1.1.3
openapi-7.0.3
org.jetbrains.annotations-1.5.0
Java SDK 1.8.0.252

do you use the same libraries?

after that I tried to compile, but the following errors appeared:
in class

AbstractCreatorAction: 
https://imgur.com/r4qxWIa
Error message: Can’t resolve method…
 

ComponentSettingsState:
https://imgur.com/2T9oRoA
Error message: Can’t find method ‘value’
 
 
can you tell me how I can fix these errors?

**Comment by faebeee** [comment]
@masteor, sorry for the late reply, just saw the issue now. 

Seems very strange to me. I'm not using either of these libs. (I'm just a web dev my self, so no expert in java)

I'll checkout the project on my new machine and try to get it running. After I get it running I'll record a video on how to set it up.
Will be able to do it this weekend.

Regards
Fabs

**Comment by faebeee** [comment]
@masteor I managed to get it up and running without any issues

Here the video which might help: https://drive.google.com/file/d/12qE2J1-GPxBwoRnNr_wL935UQ5yTlgJ_/view?usp=sharing

Closing this issue

**Comment by masteor** [comment]
Thank you very much Fabian, I was able to repeat what you did in the video, thanks again for taking the time to resolve my question
