### ISSUE TITLE
Single file component without dictionary

### ISSUE THREAD

**Issue by zhan-ge** [faebeee/vue-component-creator-plugin#15]
If it possiable to provide a way to create single file component without create the dictionary, cause I would awalys create a really single .vue file for a component to construct very simple page.

Thanks a lot, I like this plugin very much, cause I'm a backend developer and konw nothing about frontend stack...

**Comment by faebeee** [comment]
Hi @zhan-ge 

that is a good idea. I think that should be easy to implement. I'll look into it this weekend. 
It will probably become a checkbox in the settings section of the plugin

**Comment by faebeee** [comment]
@zhan-ge I've just noticed that this feature is kind of already supported by the IDE's (WebStorm at least)

I won't reimplement the same feature. But if you are missing something specific, please let me know. For now I'm closing this issue.

![Screenshot 2020-11-07 at 10 52 05](https://user-images.githubusercontent.com/1639604/98438012-5fb28000-20e7-11eb-9c24-54181b6731aa.png)

**Comment by zhan-ge** [comment]
@faebeee I'm using Intellij IDEA 2020.2, with javalin-vue framework for frontend development, which means I'll create new vue component without any modern frontend project configurations, eg. webpack.., in the src/main/resources/.. directionary.

Sorry for my crappy english, I means, I just want to create single file vue componet(without a directionary) only with this plugin installed in any directionary of any kind of project, eg. maven/sbt/gradle...,which the IDE cannot provide the creation option depends on the project build configuration file, eg. webpack...

Thanks a lot!
