### ISSUE TITLE
In mac 10.15.0, websotrm could not enter component name

### ISSUE THREAD

**Issue by StringKe** [faebeee/vue-component-creator-plugin#3]
![image](https://user-images.githubusercontent.com/31089228/65229867-88507280-daff-11e9-8419-542363575b68.png)
When I press the screenshot button and cut out the above image, there is a miracle that can be entered.

**Comment by faebeee** [comment]
Hi @StringKe I've to update my macOs for reproduction, but I'll look into it this weekend

**Comment by StringKe** [comment]
When this problem occurs, I open a phpstrom and a webstorm, and work on two screens. If you cancel the selected state of the websotrm window, the websotrm window will be restored again.

**Comment by faebeee** [comment]
I finally managed to reproduce the strange behaviour. It happens with the latest version of WebStorm and PhpStorm. I'll have to dig further

**Comment by StringKe** [comment]
I have translated the contents of the document.

**Comment by faebeee** [comment]
@StringKe what document? I'm still on this issue. Seems to be an error with the recent releases of the jetbrains tools with 2019.2.3 releases. Currently I can't even start the plugin in the development environment. I'll get in contact with jetbrains to see what might be the problem

**Comment by faebeee** [comment]
FYI: https://youtrack.jetbrains.com/issue/IDEA-224104

**Comment by paligiannis** [comment]
Same issue here. 
PHPStorm : 2019.2.5
Module: v1.1.1
**Can't write anything in inputs**

**Comment by faebeee** [comment]
It seems that jetbrains fixed the issue in the latest release. If the bug is still available reopen the issue. Closed for now

https://youtrack.jetbrains.com/issue/IDEA-224104
