### ISSUE TITLE
Vuex template types.d.ts file integration

### ISSUE THREAD

**Issue by GianlucaGuarini** [faebeee/vue-component-creator-plugin#4]
It would be cool if the vuex template could also contain `types.d.ts` out of the box. Let me know if you need a PR for it.

**Comment by faebeee** [comment]
Hi, I'll look into it. Sorry I haven't seen the issue until now

**Comment by faebeee** [comment]
AFAIK this is already implemented in v1.3.0. If the implementation doesn't suit you feel free to reopen the issue
