### ISSUE TITLE
Templates modification

### ISSUE THREAD

**Issue by ton77v** [faebeee/vue-component-creator-plugin#5]
Hi! Sorry if that's something obvious, but I can't figure out how can I modify the templates - file names and the template itself?

**Comment by faebeee** [comment]
You mean within the installed plugin (inside the IDE?) That is currently not supported. 
But you can fork the repo and do your customisations and create a new plugin from that

**Comment by ton77v** [comment]
Yeah, thanks will do this way. But it will be good to have some customization options in future releases, at least "to generate .html" and the template customization

**Comment by faebeee** [comment]
@ton77v thanks. I'll keep an eye on this feature
